In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
torch.__version__

'2.1.0'

Function to plot the vectors

In [4]:
#Plot vectors
def plotVec(vectors):
    ax = plt.axes()
    
    #For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0,0 *vec["vector"], head_width = 0.05, color = vec["color"], head_length = 0.1)
        plt.text(*(vec[vector] + 0.1), vec["name"])
        
    plt.ylim(-2,2)
    plt.xlim(-2,2)

**Types and Shapes**

In [5]:
#Convert integer list to tensor
ints_to_tensor = torch.tensor([0,1,2,3,4])
print("dtype after conversion is: ", ints_to_tensor.dtype)
print("Type after conversion is: ", ints_to_tensor.type())

dtype after conversion is:  torch.int64
Type after conversion is:  torch.LongTensor


In [6]:
type(ints_to_tensor)

torch.Tensor

In [7]:
#Convert float list to tensor
floats_to_tensor = torch.tensor([0.0,1.0,2.0,3.0,4.0])
print("dtype after conversion is: ", floats_to_tensor.dtype)
print("Type after conversion is: ", floats_to_tensor.type())

dtype after conversion is:  torch.float32
Type after conversion is:  torch.FloatTensor


In [8]:
type(floats_to_tensor)

torch.Tensor

In [9]:
#Convert an integer list with length 5 to float tensor
new_float_tensor = torch.FloatTensor([0,1,2,3,4])
new_float_tensor.type()
print("The type of the new_float_tensor:", new_float_tensor.type())

The type of the new_float_tensor: torch.FloatTensor


In [10]:
new_float_tensor = torch.FloatTensor([0,1,2,3,4])

In [13]:
#Another method to convert the integer list to float tensor
old_int_tensor = torch.tensor([0,1,2,3,4])
new_float_tensor = old_int_tensor.type(torch.FloatTensor)
print("The type of the new_float_tensor:", new_float_tensor.type())

The type of the new_float_tensor: torch.FloatTensor


<code>tensor_obj.size()</code> finds the size of the tensor_obj. <code>tensor_obj.ndimension()</code> shows the dimension of the tensor object.

In [14]:
print("Size of the new_float_tensor: ", new_float_tensor.size())
print("The dimension of the new_float_tensor: ", new_float_tensor.ndimension())

Size of the new_float_tensor:  torch.Size([5])
The dimension of the new_float_tensor:  1


<code>tensor_obj.view,</code>(row, column) is used for reshaping a tensor object
- When you execute <code>new_float_tensor.view(5,1)</code> the size will be <code>torch.Size([5,1])</code>
- Meaning the tensor object has been reshaped from a one-dimensional tensor with 5 elements to a two-dimensional tensor object with 5 rows and 1 column

In [15]:
twoD_float_tensor = new_float_tensor.view(5,1)
print("Original Size: ", new_float_tensor)
print("Size after view method", twoD_float_tensor)

Original Size:  tensor([0., 1., 2., 3., 4.])
Size after view method tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


Note: The number of elements in a tensor must remain constant after applying view

Tensors with a dynamic size can be reshaped using -1

In [16]:
#Introduce the use of -1 in tensor_obj.view(row,column) method
twoD_float_tensor = new_float_tensor.view(-1,1)
print("Original Size: ", new_float_tensor)
print("Size after view method", twoD_float_tensor)

Original Size:  tensor([0., 1., 2., 3., 4.])
Size after view method tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


-1 can represent any size. But, it can only be set for one of the values

In [17]:
#Convert a numpy array to a tensor
numpy_array = np.array([0.0,1.0,2.0,3.0,4.0])
new_tensor = torch.from_numpy(numpy_array)

print("Dtype of new tensor: ", new_tensor.dtype)
print("The type of new tensor: ", new_tensor.type())

Dtype of new tensor:  torch.float64
The type of new tensor:  torch.DoubleTensor


In [19]:
#Convert a tensor to a numpy array
back_to_numpy = new_tensor.numpy()

print("Numpy array from tensor: ", back_to_numpy)
print("Dtype of numpy arary: ", back_to_numpy.dtype)

Numpy array from tensor:  [0. 1. 2. 3. 4.]
Dtype of numpy arary:  float64


In [20]:
#Set all elements in numpy array to zero
numpy_array[:] = 0
print("The new tensor points to numpy_array: ", new_tensor)
print("and back to numpy array points to the tensor: ", back_to_numpy)

The new tensor points to numpy_array:  tensor([0., 0., 0., 0., 0.], dtype=torch.float64)
and back to numpy array points to the tensor:  [0. 0. 0. 0. 0.]


In [21]:
#Convert a panda series to a tensor

pandas_series=pd.Series([0.1,2,0.3,10.1])
new_tensor=torch.from_numpy(pandas_series.values)
print("The new tensor from numoy array: ", new_tensor)
print("The dtype of new tensor: ", new_tensor.dtype)
print("The type of new tensor: ", new_tensor.type())

The new tensor from numoy array:  tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)
The dtype of new tensor:  torch.float64
The type of new tensor:  torch.DoubleTensor


Consider The Following Tensor

In [22]:
this_tensor = torch.tensor([0,1,2,3])

The method <code>item()</code> returns the value of this tensor as a standard Python number (Only works with one element)

In [23]:
print("the first item is given by ", this_tensor[0].item(),"the first tensor value is given by ",this_tensor[0])
print("the second item is given by ", this_tensor[1].item(),"the second tensor value is given by ",this_tensor[1])
print("the third item is given by ", this_tensor[2].item(),"the third tensor value is given by ",this_tensor[2])

the first item is given by  0 the first tensor value is given by  tensor(0)
the second item is given by  1 the second tensor value is given by  tensor(1)
the third item is given by  2 the third tensor value is given by  tensor(2)


The method tolist() is used to return a list

In [24]:
torch_to_list = this_tensor.tolist()

print("tensor: ", this_tensor, "\nlist:", torch_to_list)

tensor:  tensor([0, 1, 2, 3]) 
list: [0, 1, 2, 3]


**Practice**

Try to convert <code>your_tensor</code> to a 1x5 tensor

In [33]:
your_tensor = torch.tensor([1,2,3,4,5])
your_tensor

tensor([1, 2, 3, 4, 5])

In [32]:
new_your_tensor = your_tensor.view(1,5)
new_your_tensor

tensor([[1, 2, 3, 4, 5]])

The brackets show the tensor is two dimensional

**Indexing and Slicing**

In [34]:
tensor_sample = torch.tensor([20,1,2,3,4])

Assign the value of index 0 as 100

In [35]:
#Change the value on the index 0 to 100

tensor_sample[0] = 100
print("Modified tensor", tensor_sample)

Modified tensor tensor([100,   1,   2,   3,   4])


In [36]:
#Change the value on index 4 to 0

tensor_sample[4] = 0
print("Modified tensor:", tensor_sample)

Modified tensor: tensor([100,   1,   2,   3,   0])


Get the subset of <code>tensor_sample</code>. The subset should contain the values in <code>tensor_sample</code> from index 1 to index 3.

In [37]:
#Slice tensor_sample

subset_tensor_sample = tensor_sample[1:4]
print("Original: ", tensor_sample)
print("Subset of Original: ", subset_tensor_sample)

Original:  tensor([100,   1,   2,   3,   0])
Subset of Original:  tensor([1, 2, 3])


The result only returns indexes 1 through 3

You can also assign new values to the slices

In [38]:
#Change values on index 3 and index 4

print("Original values of index 3 and 4:", tensor_sample[3:5])
tensor_sample[3:5] = torch.tensor([300.0, 400.0])
print("Modified tensor:", tensor_sample)

Original values of index 3 and 4: tensor([3, 0])
Modified tensor: tensor([100,   1,   2, 300, 400])


You can also use a variable to contain the selected indexes and pass that variable to a tensor slice operation as a parameter

In [39]:
#Using variable to contain the selected index, and pass it to slice operation

selected_indexes = [3,4]
subset_tensor_sample = tensor_sample[selected_indexes]
print("Initial tensor_sample:", tensor_sample)
print("The subset with the values on index 3 and 4:", subset_tensor_sample)

Initial tensor_sample: tensor([100,   1,   2, 300, 400])
The subset with the values on index 3 and 4: tensor([300, 400])


You can also assign one value to the selected indexes by using the variable.

In [40]:
#Using variable to assign the value to the selected indexes

print("The intial tensor_sample:", tensor_sample)
selected_indexes = [1,3]
tensor_sample[selected_indexes] = 100000
print("Modified tensor with one value:", tensor_sample)

The intial tensor_sample: tensor([100,   1,   2, 300, 400])
Modified tensor with one value: tensor([   100, 100000,      2, 100000,    400])


Note: You can only use one value for the assignment

**Practice**

Change the values on index 3,4,7 of the following tensor to 0

In [41]:
practice_tensor = torch.tensor([2,7,3,4,6,2,3,1,2])

In [42]:
indexes = [3,4,7]
practice_tensor[indexes] = 0
practice_tensor

tensor([2, 7, 3, 0, 0, 2, 3, 0, 2])